# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main_window.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('ui_main.py', '.'),
        ('feature_matcher.py', '.'),
        ('test_my_data.py', '.'),
        ('config_manager.py', '.'),
        ('config.json', '.'),
        ('history_manager.py', '.'),
        ('history_window.py', '.'),
        ('history.json', '.'),
        ('utils/image_io.py', 'utils'),
        ('core/__init__.py', 'core'),
        ('core/homography_estimator.py', 'core'),
        ('core/image_warper.py', 'core'),
        ('core/image_blender.py', 'core'),
        ('shared_types.py', '.'),
        ('config.py', '.'),
    ],
    hiddenimports=[
        'cv2',
        'cv2.detail',
        'numpy',
        'numpy.core',
        'numpy.core.multiarray',
        'numpy.lib',
        'json',
        'os',
        'sys',
        'io',
        'time',
        'uuid',
        'typing',
        'datetime',
        're',
        'PySide6',
        'PySide6.QtWidgets',
        'PySide6.QtCore',
        'PySide6.QtGui',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='PanoramaStitcher',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='PanoramaStitcher',
)
